Use modern cmake targets to avoid absolute paths to appear in binary archives
ros2/rosidl_python pull request #160
Opened 2022-05-02 18:13 UTC by ivanpauno

* Move logic to find Numpy headers to a module and export a target fr…om there.

* Use the new NumpyHeaders::NumpyHeaders and PythonExtra::PythonExtra to avoid absolute paths to appear in windows binary archives.

2022-05-02 18:19 UTC, ivanpauno commented
Windows packaging CI after this change: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=198)](http://ci.ros2.org/job/ci_packaging_windows/198/)

2022-05-02 19:17 UTC, ivanpauno commented
Let's see if I have more luck now: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=199)](http://ci.ros2.org/job/ci_packaging_windows/199/)

2022-05-02 20:43 UTC, ivanpauno commented
Third time is the charm (?): [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=201)](http://ci.ros2.org/job/ci_packaging_windows/201/)

2022-05-03 14:44 UTC, ivanpauno commented
I downloaded the binary archive, and it works!!!
Now there're a lot less absolute paths in the provided binaries.

2022-05-03 20:10 UTC, clalancette approved these changes
Overall, this looks good to me with green CI on all platforms (including RHEL and Windows Debug).  I'd like to get a second opinion from @sloretz before we merge, though.

That said, this seems pretty risky to me to put into Humble.  This is deep in the heart of the message generation, and we don't know the unintended side effects of this.  So my suggestion is that we do indeed put it into Rolling, but we do not backport to Humble.  I'd be happy to hear other opinions, though.

2022-05-03 20:10 UTC, clalancette commented on rosidl_generator_py/cmake/FindNumpyHeaders.cmake
> +endif()
Nit: add trailing newline here.

2022-05-03 21:34 UTC, sloretz requested changes
In [CMake 3.14 and above, `Python3::NumPy`](https://cmake.org/cmake/help/latest/module/FindPython3.html) can be used, and looking at `webos OSE` I think we can use that here https://github.com/ros-infrastructure/rep/pull/351

2022-05-12 16:06 UTC, ivanpauno commented
> In [CMake 3.14 and above, Python3::NumPy](https://cmake.org/cmake/help/latest/module/FindPython3.html) can be used, and looking at webos OSE I think we can use that here https://github.com/ros-infrastructure/rep/pull/351

Thanks, I'm not sure why I didn't see that before.

2022-05-12 16:10 UTC, ivanpauno commented
> That said, this seems pretty risky to me to put into Humble. This is deep in the heart of the message generation, and we don't know the unintended side effects of this.

I think it's safe to backport.
The libraries generated here are only loaded from python to bind with the rosidl_generator_c interface, but nothing depends on them, so we actually don't even need to export the cmake targets.

2022-05-12 16:11 UTC, ivanpauno commented
Windows packaging job: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=201)](http://ci.ros2.org/job/ci_packaging_windows/201/)

2022-05-12 16:13 UTC, ivanpauno commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16688)](http://ci.ros2.org/job/ci_linux/16688/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11275)](http://ci.ros2.org/job/ci_linux-aarch64/11275/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17089)](http://ci.ros2.org/job/ci_windows/17089/)

2022-05-12 16:52 UTC, sloretz commented
* Linux re-run [![Build Status](https://ci.ros2.org/job/ci_linux/16689/badge/icon)](https://ci.ros2.org/job/ci_linux/16689/)

2022-05-12 16:54 UTC, sloretz approved these changes
LGTM for Rolling and Humble backport when CI comes back green.

2022-05-13 17:41 UTC, merged

2022-05-13 17:41 UTC, ivanpauno commented
@mergifyio backport humble