Improve message types.
ros2/rosidl_python pull request #206
Opened 2024-03-15 06:48 UTC by InvincibleRMC

Adds some static typing to generated messages. Built off #205.

2024-03-15 07:13 UTC, InvincibleRMC commented
Still need to fix a circular import issue.

2024-03-19 23:34 UTC, InvincibleRMC commented
Running mypy complains about the type change within ` @property`  this doesn't effect the end user and is fine for now until [#mypy300](https://github.com/python/mypy/issues/3004) gets resolved.

2024-05-21 00:33 UTC, haudren-woven commented
Very nice! There is another working package here:
https://github.com/rospypi/rosidl_generator_mypy

I hope this can be merged and replace the above :pray: Thank you for working on type annotations.

2024-05-24 00:18 UTC, InvincibleRMC commented
> Very nice! There is another working package here: https://github.com/rospypi/rosidl_generator_mypy
> 
> I hope this can be merged and replace the above 🙏 Thank you for working on type annotations.

If your solutions works and gets merged in I will gladly close this pr.

2024-05-27 05:10 UTC, haudren-woven commented
Actually our solution is meant as a placeholder which you can use in your own workspace without modifying `rosidl_generator_py`. Last time we tried to PR this in, the maintainers did not seem to have much interest in merging it, but I'm supportive to merge your solution in: I'd rather focus our contributions on a core package such that it can benefit the larger community. From my cursory look, they look rather equivalent so let's go with it :+1:

2024-11-26 19:12 UTC, InvincibleRMC commented
One thing I have learn which is relevant to #216 is that currently according to pep [484](https://peps.python.org/pep-0484/#the-numeric-tower) is that a type annotation of `float` allows `int`. There is currently no defined way to define a `realFloat` type that disallows `int`. There are many discussions about [this](https://discuss.python.org/t/options-for-a-long-term-fix-of-the-special-case-for-float-int-complex/54289?page=2).

2025-01-27 17:55 UTC, InvincibleRMC commented
@sloretz @fujitatomoya could you review this pull request if you get the chance? It would improve the pub/sub, service/clients in `rclpy` since currently the generics are being ignored.

2025-03-13 23:42 UTC, sloretz requested changes
Thank you for the PR! It's no small feat to make changes to the empy templates 🙇 

I'm still looking through the changes in `_msg.py.em`, but I have some feedback in the meantime.

2025-03-13 23:42 UTC, sloretz commented on rosidl_generator_py/rosidl_generator_py/__init__.py
> +    generate_py
The line was `assert generate_py` before, but I'm not really sure that line was meaningful. I recommend deleting the line instead of leaving the statement `generate_py`.

2025-03-13 23:42 UTC, sloretz commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +                    f'{idl_stem} as {idl_stem}  # noqa: F401\n')
What does adding the `as` keyword here do? It looks like the name is unchanged in all of the lines in this file.

2025-03-13 23:42 UTC, sloretz commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +        pass
Recommend [`pathlib.Path.touch`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.touch) instead of `with open(...): pass`

2025-03-13 23:42 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +            from rosidl_generator_py.rosidl_generator_py import import_type_support
I think this import is incorrect

```python3
>>> from rosidl_generator_py.rosidl_generator_py import import_type_support
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rosidl_generator_py.rosidl_generator_py'
>>> from rosidl_generator_py import import_type_support
>>> 
```

2025-03-13 23:42 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +    def __init__(self,
Please add `*,` here to force the arguments to be keyword only to avoid downstream code relying on the order of fields, and breaking if the message fields are added or reordered.

```suggestion
    def __init__(self, *,
```

2025-03-13 23:42 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) or @(message.structure.namespaced_type.name).@(member.name.upper())__DEFAULT
Please check if the values are `None` instead of using `or`

```suggestion
        if 
        self.@(member.name) = @(member.name) if @(member.name) is not None else @(message.structure.namespaced_type.name).@(member.name.upper())__DEFAULT
```

Using `or` has an issue when default value evaluates to `True` but the value provided to `__init__` evaluates as False. For example, `Defaults.msg` has a field called `bool_value` with a default value of `true`: https://github.com/ros2/test_interface_files/blob/25d4b699e4bcd28ab4d900dd73540ea341b8c508/msg/Defaults.msg#L1

Using `or`, the line becomes:

```python3
self.bool_value = bool_value or Defaults.BOOL_VALUE__DEFAULT
```

If the user calls `Defaults(bool_value=False)`, then `self.bool_value = bool_value or Defaults.BOOL_VALUE__DEFAULT` becomes `self.bool_value = False or True` -> `self.bool_value = True`

2025-03-14 00:28 UTC, InvincibleRMC commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +                    f'{idl_stem} as {idl_stem}  # noqa: F401\n')
By default type checkers typically want imports from where classes are defined. So by default it would want `from rosidl_generator_py.msg._arrays import Arrays`. Using `as` re-exports it so it can be imported from a different file. This could also be exported using `__all__ = ['Arrays']`.

2025-03-14 15:45 UTC, sloretz commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +                    f'{idl_stem} as {idl_stem}  # noqa: F401\n')
Ah I did not know that!

2025-03-14 15:56 UTC, sloretz reviewed
Few more places to use `if @(member.name) is not None else` instead of `or`

2025-03-14 15:56 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) or [bytes([0]) for x in range(@(member.type.size))]
```suggestion
        self.@(member.name) = @(member.name) if @(member.name) is not None else [bytes([0]) for x in range(@(member.type.size))]
```

2025-03-14 15:56 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) or [chr(0) for x in range(@(member.type.size))]
```suggestion
        self.@(member.name) = @(member.name) if @(member.name) is not None else [chr(0) for x in range(@(member.type.size))]
```

2025-03-14 15:56 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) or [@(get_python_type(type_))() for x in range(@(member.type.size))]
```suggestion
        self.@(member.name) = @(member.name) if @(member.name) is not None else [@(get_python_type(type_))() for x in range(@(member.type.size))]
```

2025-03-14 15:56 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) or array.array('@(SPECIAL_NESTED_BASIC_TYPES[member.type.value_type.typename]['type_code'])', [])
```suggestion
        self.@(member.name) = @(member.name) if @(member.name) is not None else array.array('@(SPECIAL_NESTED_BASIC_TYPES[member.type.value_type.typename]['type_code'])', [])
```

2025-03-14 15:56 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) or []
```suggestion
        self.@(member.name) = @(member.name) if @(member.name) is not None else []
```

2025-03-14 15:56 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) or bytes([0])
```suggestion
        self.@(member.name) = @(member.name) if @(member.name) is not None else bytes([0])
```

2025-03-14 15:56 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) or chr(0)
```suggestion
        self.@(member.name) = @(member.name) if @(member.name) is not None else chr(0)
```

2025-03-14 15:56 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) or @(get_python_type(type_))()
```suggestion
        self.@(member.name) = @(member.name) if @(member.name) is not None else @(get_python_type(type_))()
```

2025-03-14 18:02 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +@[end for]
Actions and services import the `_msg.py.em` template. That causes this block to get included in the file twice, and that causes linter test failures. You can reproduce by testing the `action_msgs` package with this PR.

Example: 
https://github.com/ros2/rosidl_python/blob/1d4a4c74c674558d781606be7e32cced4b6bc5f6/rosidl_generator_py/resource/_action.py.em#L8-L32

I'm not sure how to fix this. Maybe we could gather the type annotation information from all messages, and then generate the type annotation imports in a separate template? Something like

```python
type_annotation_info = gather_type_annotations(...)
TEMPLATE('_type_annotation_imports.py.em', 
 type_annotation_info=type_annotation_info, ...)
TEMPLATE('_msg_classes.py.em', 
 type_annotation_info=type_annotation_info, ...)
TEMPLATE('_msg_classes.py.em', 
 type_annotation_info=type_annotation_info, ...)
# ...
``` 

<details><summary>action_msgs.srv._cancel_goal.py</summary>

```python
# generated from rosidl_generator_py/resource/_idl.py.em
# with input from action_msgs:srv/CancelGoal.idl
# generated code does not contain a copyright notice

# This is being done at the module level and not on the instance level to avoid looking
# for the same variable multiple times on each instance. This variable is not supposed to
# change during runtime so it makes sense to only look for it once.
from collections.abc import MutableMapping
from os import getenv
from typing import Any, ClassVar, Dict, Optional, Tuple, Type, TYPE_CHECKING, TypedDict

ros_python_check_fields = getenv('ROS_PYTHON_CHECK_FIELDS', default='')
if TYPE_CHECKING:
    from ctypes import Structure

    class PyCapsule(Structure):
        pass  # don't need to define the full structure

    from action_msgs.msg import GoalInfo

# Import statements for member types

import builtins  # noqa: E402, I100

import rosidl_parser.definition  # noqa: E402, I100


class Metaclass_CancelGoal_Request(type):
    """Metaclass of message 'CancelGoal_Request'."""

    _CREATE_ROS_MESSAGE: ClassVar[Optional['PyCapsule']] = None
    _CONVERT_FROM_PY: ClassVar[Optional['PyCapsule']] = None
    _CONVERT_TO_PY: ClassVar[Optional['PyCapsule']] = None
    _DESTROY_ROS_MESSAGE: ClassVar[Optional['PyCapsule']] = None
    _TYPE_SUPPORT: ClassVar[Optional['PyCapsule']] = None

    class CancelGoal_RequestConstants(TypedDict):
        pass

    __constants: CancelGoal_RequestConstants = {
    }

    class CancelGoal_RequestDefault(CancelGoal_RequestConstants):
        pass

    @classmethod
    def __import_type_support__(cls) -> None:
        try:
            from rosidl_generator_py import import_type_support
            module = import_type_support('action_msgs')
        except ImportError:
            import logging
            import traceback
            logger = logging.getLogger(
                'action_msgs.srv.CancelGoal_Request')
            logger.debug(
                'Failed to import needed modules for type support:\n' +
                traceback.format_exc())
        else:
            cls._CREATE_ROS_MESSAGE = module.create_ros_message_msg__srv__cancel_goal__request
            cls._CONVERT_FROM_PY = module.convert_from_py_msg__srv__cancel_goal__request
            cls._CONVERT_TO_PY = module.convert_to_py_msg__srv__cancel_goal__request
            cls._TYPE_SUPPORT = module.type_support_msg__srv__cancel_goal__request
            cls._DESTROY_ROS_MESSAGE = module.destroy_ros_message_msg__srv__cancel_goal__request

            from action_msgs.msg import GoalInfo
            if GoalInfo._TYPE_SUPPORT is None:
                GoalInfo.__import_type_support__()

    @classmethod
    def __prepare__(metacls, name: str, bases: Tuple[Type[Any], ...], /, **kwds: Any) -> MutableMapping[str, object]:
        # list constant names here so that they appear in the help text of
        # the message class under "Data and other attributes defined here:"
        # as well as populate each message instance
        return {
        }


class CancelGoal_Request(metaclass=Metaclass_CancelGoal_Request):
    """Message class 'CancelGoal_Request'."""

    __slots__ = [
        '_goal_info',
        '_check_fields',
    ]

    _fields_and_field_types: Dict[str, str] = {
        'goal_info': 'action_msgs/GoalInfo',
    }

    # This attribute is used to store an rosidl_parser.definition variable
    # related to the data type of each of the components the message.
    SLOT_TYPES: Tuple[rosidl_parser.definition.AbstractType, ...] = (
        rosidl_parser.definition.NamespacedType(['action_msgs', 'msg'], 'GoalInfo'),  # noqa: E501
    )

    def __init__(self, *,
                 goal_info: Optional['GoalInfo'] = None,  # noqa: E501
                 check_fields: Optional[bool] = None) -> None:
        if check_fields is not None:
            self._check_fields = check_fields
        else:
            self._check_fields = ros_python_check_fields == '1'
        from action_msgs.msg import GoalInfo
        self.goal_info = goal_info if goal_info is not None else GoalInfo()

    def __repr__(self) -> str:
        typename = self.__class__.__module__.split('.')
        typename.pop()
        typename.append(self.__class__.__name__)
        args = []
        for s, t in zip(self.get_fields_and_field_types().keys(), self.SLOT_TYPES):
            field = getattr(self, s)
            fieldstr = repr(field)
            # We use Python array type for fields that can be directly stored
            # in them, and "normal" sequences for everything else.  If it is
            # a type that we store in an array, strip off the 'array' portion.
            if (
                isinstance(t, rosidl_parser.definition.AbstractSequence) and
                isinstance(t.value_type, rosidl_parser.definition.BasicType) and
                t.value_type.typename in ['float', 'double', 'int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64']
            ):
                if len(field) == 0:
                    fieldstr = '[]'
                else:
                    if self._check_fields:
                        assert fieldstr.startswith('array(')
                    prefix = "array('X', "
                    suffix = ')'
                    fieldstr = fieldstr[len(prefix):-len(suffix)]
            args.append(s + '=' + fieldstr)
        return '%s(%s)' % ('.'.join(typename), ', '.join(args))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, CancelGoal_Request):
            return False
        if self.goal_info != other.goal_info:
            return False
        return True

    @classmethod
    def get_fields_and_field_types(cls) -> Dict[str, str]:
        from copy import copy
        return copy(cls._fields_and_field_types)

    @builtins.property
    def goal_info(self) -> 'GoalInfo':
        """Message field 'goal_info'."""
        return self._goal_info

    @goal_info.setter
    def goal_info(self, value: 'GoalInfo') -> None:
        if self._check_fields:
            from action_msgs.msg import GoalInfo
            assert \
                isinstance(value, GoalInfo), \
                "The 'goal_info' field must be a sub message of type 'GoalInfo'"
        self._goal_info = value
if TYPE_CHECKING:
    from ctypes import Structure

    class PyCapsule(Structure):
        pass  # don't need to define the full structure

    from action_msgs.msg import GoalInfo
    from typing import Literal
    from collections.abc import Sequence
    from collections import UserList
    from collections.abc import Set
    from typing import Union

# Import statements for member types

# already imported above
# import builtins

# already imported above
# import rosidl_parser.definition


class Metaclass_CancelGoal_Response(type):
    """Metaclass of message 'CancelGoal_Response'."""

    _CREATE_ROS_MESSAGE: ClassVar[Optional['PyCapsule']] = None
    _CONVERT_FROM_PY: ClassVar[Optional['PyCapsule']] = None
    _CONVERT_TO_PY: ClassVar[Optional['PyCapsule']] [...]

2025-03-14 18:05 UTC, sloretz commented on rosidl_generator_py/resource/_msg.py.em
> +@[end for]
I guess there's already a pattern to fix this, it's the passing in of import statements into the template:

https://github.com/ros2/rosidl_python/blob/1d4a4c74c674558d781606be7e32cced4b6bc5f6/rosidl_generator_py/resource/_msg.py.em#L77-L78

If we keep a `type_annotations_import_statements` list, then we can do the same thing.

2025-03-14 20:04 UTC, InvincibleRMC commented on rosidl_generator_py/resource/_msg.py.em
> +@[end for]
I have started working on this. Will push once it works.

2025-03-22 18:44 UTC, InvincibleRMC commented
@sloretz Following up I was able to remove the duplicate imports. Let me know if there are any other questions/suggestions. Thanks again for reviewing this pr.

2025-05-20 17:40 UTC, InvincibleRMC commented
Now that kilted is starting to wrap up friendly ping @sloretz to re-review when you get a chance.

2025-06-18 19:24 UTC, InvincibleRMC commented
Friendly ping @sloretz to finish the review when you get a chance.

2025-07-11 00:40 UTC, ros-discourse commented
This pull request has been mentioned on **Open Robotics Discourse**. There might be relevant details there:

https://discourse.ros.org/t/python-generated-messages-with-static-type-hints/45156/1

2025-07-19 19:01 UTC, benjaminwp18 requested changes

2025-07-19 19:01 UTC, benjaminwp18 commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +        type_annotation = 'typing.Union[bytes, collections.abc.ByteString]'
Should the duplicate `isinstance(member.type, AbstractNestedType)` and `isinstance(type_, BasicType)` cases be combined here?

2025-07-19 19:01 UTC, benjaminwp18 commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +    elif isinstance(constant.type, AbstractNestedType):
Should the duplicate `isinstance(constant.type, AbstractNestedType)` cases be combined here?

2025-07-19 19:01 UTC, benjaminwp18 commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +def get_type_annotation_constant_default(constant: Constant, value: Union[str, int, float, bool],
Consider adding a docstring

2025-07-19 19:01 UTC, benjaminwp18 commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +def get_setter_and_getter_type(member: Member, type_imports: set[str]) -> tuple[str, str]:
Consider adding a docstring

2025-07-19 20:12 UTC, InvincibleRMC commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +        type_annotation = 'typing.Union[bytes, collections.abc.ByteString]'
Since isinstance checks do type narrowing combining them would lose some typing information.

2025-07-19 20:12 UTC, InvincibleRMC commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +    elif isinstance(constant.type, AbstractNestedType):
Since isinstance checks do type narrowing combining them would lose some typing information.

2025-07-19 21:09 UTC, InvincibleRMC commented
@benjaminwp18 Thanks so much for the review. I have addressed your feedback. Please let me know if you have any other feedback.

2025-07-19 21:30 UTC, InvincibleRMC commented
@christophebedard when you get a chance I would appreciate a ROS Maintainer review as well.

2025-07-22 20:26 UTC, christophebedard commented on rosidl_generator_py/resource/_msg.py.em
> +}@
This is pretty dangerous from a legal/licensing point of view, since the `flake8-builtins` code is [GPLv2-licensed](https://github.com/gforcada/flake8-builtins/blob/689ad01c03cb52ae73be23d19706e6a4a491f4e9/LICENSE). GPLv2 and other copyleft licenses require that any "derivative work" be also licensed GPLv2 ("GPL virality").

Please rewrite this so that the code isn't just copied from a GPLv2-licensed file.

2025-07-22 20:26 UTC, christophebedard commented on rosidl_generator_py/resource/_msg.py.em
> -
What is the reason for removing this? I think it's meant to keep a normal 2-line separation between sections in the generated file(?).

2025-07-22 21:32 UTC, InvincibleRMC commented on rosidl_generator_py/resource/_msg.py.em
> -
added back

2025-07-22 21:34 UTC, InvincibleRMC commented on rosidl_generator_py/resource/_msg.py.em
> +}@
Ok I rewrote it based on the already existing builtins handler in `_msg.py.em` seen [here](https://github.com/ros2/rosidl_python/blob/4dda0a4777dff29d1e95d6123cc38c6d9a9bdba3/rosidl_generator_py/resource/_msg.py.em#L423-L432)

2025-07-22 22:01 UTC, christophebedard commented on rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
> +      TESTNAME "mypy_rosidl_generate_py"
To match the other `*_rosidl_generated_py` test names:

```suggestion
      TESTNAME "mypy_rosidl_generated_py"
```

2025-07-22 22:01 UTC, christophebedard commented on rosidl_generator_py/resource/_idl.py.em
>  ros_python_check_fields = getenv('ROS_PYTHON_CHECK_FIELDS', default='')
I think the comment is referring to this `ros_python_check_fields` line. Since you're adding some imports, can you move the 3 comment lines so that they are above this line? Otherwise it might be a bit confusing

2025-07-22 22:01 UTC, christophebedard commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +       type_.typename in SPECIAL_NESTED_BASIC_TYPES:
Minor comment, feel free to ignore:

Personally, I'm a fan of `if (...):` for readability (I think the `and` goes at the end of the previous line and not at the beginning of the next line, but I'm not 100% sure):

```suggestion
    if (
        isinstance(constant.type, AbstractNestedType) and isinstance(type_, BasicType) and
        type_.typename in SPECIAL_NESTED_BASIC_TYPES
    ):
```

2025-07-22 22:01 UTC, christophebedard commented on rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
> +       type_.typename in SPECIAL_NESTED_BASIC_TYPES:
Similar to my other minor comment, I'd suggest using `if (...):`, but it's up to you.

2025-07-22 22:03 UTC, christophebedard commented on rosidl_generator_py/resource/_action.py.em
> +type_annotations_import_statements.add(f'from {'.'.join(action.namespaced_type.namespaces)}.{module_name} import {action.feedback.structure.namespaced_type.name}')
Don't you need to use double quotes inside of the single-quote f-string?

2025-07-22 22:29 UTC, InvincibleRMC commented on rosidl_generator_py/resource/_action.py.em
> +type_annotations_import_statements.add(f'from {'.'.join(action.namespaced_type.namespaces)}.{module_name} import {action.feedback.structure.namespaced_type.name}')
From what I can tell its fine. Even on older python versions. https://mypy-play.net/?mypy=1.17.0&python=3.9&gist=701dd3aa4272078921dca20a46e1eb04

2025-07-22 22:39 UTC, christophebedard commented on rosidl_generator_py/resource/_action.py.em
> +type_annotations_import_statements.add(f'from {'.'.join(action.namespaced_type.namespaces)}.{module_name} import {action.feedback.structure.namespaced_type.name}')
:exploding_head: alright then!

2025-07-22 22:47 UTC, christophebedard commented
Pulls: ros2/rosidl_python#206
Gist: https://gist.githubusercontent.com/christophebedard/9a392164fa167b98f745f9a505a40a73/raw/1cb2fe9a7ed734bbd4a459211613e40209a97991/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16562
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24404)](http://ci.ros2.org/job/ci_linux/24404/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18474)](http://ci.ros2.org/job/ci_linux-aarch64/18474/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3849)](http://ci.ros2.org/job/ci_linux-rhel/3849/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=24969)](http://ci.ros2.org/job/ci_windows/24969/)

2025-07-22 22:50 UTC, christophebedard commented
I ran full CI^ so that interfaces get generated, and so that hopefully the linters (including mypy) run on the generated files as part of tests in the various interface packages. The Rpr job doesn't really test much here.

2025-07-22 22:53 UTC, InvincibleRMC commented
Thanks so much for the review!

> I ran full CI^ so that interfaces get generated, and so that hopefully the linters (including mypy) run on the generated files as part of tests in the various interface packages. The Rpr job doesn't really test much here.

I was going to ask about this since I have a feeling this will expose some downstream bugs to be fixed.

2025-07-22 23:44 UTC, InvincibleRMC commented on rosidl_generator_py/resource/_action.py.em
> +type_annotations_import_statements.add(f'from {'.'.join(action.namespaced_type.namespaces)}.{module_name} import {action.feedback.structure.namespaced_type.name}')
Apparently I'm incorrect and also seem to misunderstand how mypy playground works. Will fix `rhel`

2025-07-23 15:33 UTC, christophebedard commented
Pulls: ros2/rosidl_python#206
Gist: https://gist.githubusercontent.com/christophebedard/23340b5f0c0b1e577396c407ded46165/raw/1cb2fe9a7ed734bbd4a459211613e40209a97991/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16581
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24425)](http://ci.ros2.org/job/ci_linux/24425/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18495)](http://ci.ros2.org/job/ci_linux-aarch64/18495/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3870)](http://ci.ros2.org/job/ci_linux-rhel/3870/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=24988)](http://ci.ros2.org/job/ci_windows/24988/)

2025-07-23 22:59 UTC, InvincibleRMC commented
Another old mypy bug.

```python
import typing

class A:

    def __init__(self) -> typing.NoReturn:   # The return type of "__init__" must be None
        raise NotImplementedError()
```

Will add a # type: ignore for now. Cannot wait for `rhel 10`.

2025-07-24 21:40 UTC, christophebedard commented on rosidl_generator_py/resource/_action.py.em
> +    def __init__(self) -> typing.NoReturn:  # type: ignore
If we have to ignore typing for this line due to a mypy bug, can you mention that (and the mypy bug number) in a comment (maybe right after "ignore") so that we can remove this later? Same for `rosidl_generator_py/resource/_srv.py.em`

2025-07-24 22:18 UTC, InvincibleRMC commented on rosidl_generator_py/resource/_action.py.em
> +    def __init__(self) -> typing.NoReturn:  # type: ignore
It seems like there comment parsing cannot support that. https://mypy-play.net/?mypy=latest&python=3.12&gist=b4d9d618f1831fdb30dc5dcc768a499f I'll add it above for now

2025-07-24 22:34 UTC, christophebedard commented
Pulls: ros2/rosidl_python#206
Gist: https://gist.githubusercontent.com/christophebedard/6ea01a76e36980e450b65455f81bcd72/raw/1cb2fe9a7ed734bbd4a459211613e40209a97991/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16607
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24456)](http://ci.ros2.org/job/ci_linux/24456/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18521)](http://ci.ros2.org/job/ci_linux-aarch64/18521/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3900)](http://ci.ros2.org/job/ci_linux-rhel/3900/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25014)](http://ci.ros2.org/job/ci_windows/25014/)

2025-07-25 04:45 UTC, InvincibleRMC commented
`rhel` strikes again 😢

2025-07-25 20:35 UTC, christophebedard commented
@ros-pull-request-builder retest this please

2025-07-25 21:43 UTC, christophebedard commented
Alright, let's try a full CI run again.

2025-07-25 21:44 UTC, christophebedard commented
Pulls: ros2/rosidl_python#206
Gist: https://gist.githubusercontent.com/christophebedard/1f6a02ffe82ec8f80bdc504b48fab103/raw/1cb2fe9a7ed734bbd4a459211613e40209a97991/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16612
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24471)](http://ci.ros2.org/job/ci_linux/24471/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18527)](http://ci.ros2.org/job/ci_linux-aarch64/18527/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3922)](http://ci.ros2.org/job/ci_linux-rhel/3922/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25022)](http://ci.ros2.org/job/ci_windows/25022/)

2025-07-27 17:04 UTC, InvincibleRMC commented
@christophebedard the `rhel` CI crashed can you restart it when you get a chance.

2025-07-27 19:10 UTC, christophebedard commented
It usually gets automatically retried if it fails due to an infra issue, but it's not always easy to find the corresponding job.

ci_linux-rhel 3922 was retried with 3925, which also failed due to an infra issue and was retried with 3929: https://ci.ros2.org/job/ci_linux-rhel/3929/. There's a `ros2topic` test failure, which is slightly suspicious. It's hard to tell what went wrong, but it could be due to the potential crosstalk we've been seeing. Let's retry it: Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3942)](http://ci.ros2.org/job/ci_linux-rhel/3942/)

2025-07-28 15:23 UTC, christophebedard commented
The RHEL job had some different test failures; I don't think it's related to these changes. The first one seems to be Zenoh router-related and the second one seems to be a time-related flake.

2025-07-28 15:45 UTC, christophebedard commented
@sloretz do you want to give this another look? Otherwise, I would go ahead and approve + merge it.

2025-08-01 18:22 UTC, christophebedard approved these changes

2025-08-01 18:24 UTC, merged

2025-08-02 00:04 UTC, InvincibleRMC commented
Thanks so much for all the reviews and finally getting this merged!

2025-08-04 16:18 UTC, christophebedard commented
I created a new release (`0.26.0`): https://github.com/ros/rosdistro/pull/47213.

The timing is great, because a [Rolling sync was just completed](https://discourse.openrobotics.org/t/new-packages-for-ros-2-rolling-ridley-2025-08-03/49406), so we'll have time to let the buildfarm rebuild downstream packages and fix anything that breaks.

2025-08-04 16:23 UTC, InvincibleRMC commented
Feel free to ping me about any downstream problems you find.

2026-04-07 15:33 UTC, peci1 reviewed
This PR (and not only this one, but this one is the major contributor) imposes new constraints on the names of messages.

I've reported the problem in https://github.com/ros2/rosidl_python/issues/257 . I used the review feature on this PR to highlight the places where I see problems (only in msg.em for simplicity).

2026-04-07 15:33 UTC, peci1 commented on rosidl_generator_py/resource/_msg.py.em
> +                 @(member.name): typing.Optional[@(type_annotations_setter[member.name])] = None,  # noqa: E501@(noqa_string)
This pollutes global namespace

2026-04-07 15:33 UTC, peci1 commented on rosidl_generator_py/resource/_msg.py.em
This pollutes local namespace

2026-04-07 15:33 UTC, peci1 commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) if @(member.name) is not None else @(get_python_type(type_))()
This requires polluted local namespace

2026-04-07 15:33 UTC, peci1 commented on rosidl_generator_py/resource/_msg.py.em
> +        self.@(member.name) = @(member.name) if @(member.name) is not None else [@(get_python_type(type_))() for x in range(@(member.type.size))]
This requires polluted local namespace

2026-04-07 15:33 UTC, peci1 commented on rosidl_generator_py/resource/_msg.py.em
> +    def @(member.name)(self) -> @(type_annotations_getter[member.name]):@(noqa_string)@(array_type_commment)
This requires polluted global namespace

2026-04-07 15:33 UTC, peci1 commented on rosidl_generator_py/resource/_msg.py.em
> +    def @(member.name)(self, value: @(type_annotations_setter[member.name])) -> None:@(noqa_string)
This requires polluted global namespace

2026-04-07 15:33 UTC, peci1 commented on rosidl_generator_py/resource/_msg.py.em
This pollutes local namespace

2026-04-07 15:33 UTC, peci1 commented on rosidl_generator_py/resource/_msg.py.em
This requires polluted local namespace

2026-04-07 15:33 UTC, peci1 commented on rosidl_generator_py/resource/_msg.py.em
This requires polluted local namespace